---
server:
  port: 8080
  max_clients: 100
  client:
    cors: "http://localhost:3000"
    timeout: 15000 #milliseconds
    repeat_msg: 250 #milliseconds
max_users: 4   
manager:
  redis_uri: "tcp://localhost:6331"
  lobby:
    refresh_list: 3000 #milliseconds
  game:
    game_collector: 30000 #milliseconds